name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Create file'
        uses: DamianReeves/write-file-action@master
        with:
          path: code/Config.py
          contents: |
            ${{ secrets.FIREBASE }}
          write-mode: preserve

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}